### ISSUE TITLE
TypeError: Textbox.__init__() got an unexpected keyword argument 'default'

### ISSUE THREAD

**Issue by zjiang4** [AspadaX/Thinker_DecisionMakingAssistant#1]
Help！ I got this error and can't fix it. I follow the instruction but got this。

Traceback (most recent call last):
  File "D:\LLMs\Thinker_DecisionMakingAssistant\Thinker_DecisionMakingAssistant-main\user_interface.py", line 62, in <module>
    gr.components.Textbox(
  File "d:\anaconda3\Lib\site-packages\gradio\component_meta.py", line 160, in wrapper
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: Textbox.__init__() got an unexpected keyword argument 'default'
INFO:httpx:HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"

(base) D:\LLMs\Thinker_DecisionMakingAssistant\Thinker_DecisionMakingAssistant-main>python user_interface.py
Traceback (most recent call last):
  File "D:\LLMs\Thinker_DecisionMakingAssistant\Thinker_DecisionMakingAssistant-main\user_interface.py", line 62, in <module>
    gr.components.Textbox(
  File "d:\anaconda3\Lib\site-packages\gradio\component_meta.py", line 160, in wrapper
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: Textbox.__init__() got an unexpected keyword argument 'default'

**Comment by zjiang4** [comment]
有偿咨询！谢谢您！Wechat: StanDCM

**Comment by AspadaX** [comment]
抱歉，最近事情比较多，没有关注。gradio 的版本号是多少呢

**Comment by AspadaX** [comment]
https://github.com/AspadaX/Thinker/commit/ffe9b766ee1c9166e35ac7d66112b236cce893bf

Issue has been fixed in this commit.
